project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Schedule.qmd
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Thanks for investigating"
    type: info
    position: below-navbar  
  title: "Cytometry in R"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - href: index.qmd
        text: Home
      - text: "Schedule"
        menu: 
        - text: "Schedule"
          href: Schedule.qmd
    right:
    - icon: github
      href: https://github.com/UMGCCFCSS/CytometryInR
      aria-label: GitHub
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: |
    ![AGPL-3.0](/images/AGPL3.png)
    ![CC-BY-SA](/images/CCBYSA.png)
format:
  html:
    css: styles.css

